projects:
  mvpboomrngmob:
    schemaPath: amplify/backend/api/mvpboomrngmob/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: /graphql
        region: us-east-2
        apiId: null
        maxDepth: 3
